name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - uses: actions/cache@v1
        id: cache-build
        with:
          path: "."
          key: ${{ github.sha }}

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: ${{ github.sha }}
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: ${{ github.sha }}
      - name: set ava envs
        env:
          TS_NODE_PROJECT: "tsconfig.dev.json"
      - run: yarn test

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v1
        id: restore-build
        with:
          path: "."
          key: ${{ github.sha }}
      - name: set ava envs
        env:
          TS_NODE_PROJECT: "tsconfig.dev.json"
      - run: yarn test:coverage
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
